###
# .verificaAcesso
# params: token, ativo
# necessário usuário estar logado (token)
GET	http://localhost:3333/acessos/concessoes?ativo=1&token=localhost

###
# .findPermissoesUsuario
# params: token
# necessário usuário estar logado (token)
GET	http://localhost:3333/acessos/permissoes?token=localhost

###
# .findTiposAcesso
# params: token
# necessário usuário estar logado (token)
GET	http://localhost:3333/acessos/tipos?token=localhost

###
# .revogarAcessosAutomaticamente
# params: none
GET	http://localhost:3333/acessos/removerAutomatico

###
# .deleteConcessaoAcesso
# params: id, token
# necessário usuário estar logado (token)
DELETE http://localhost:3333/acessos/concessoes/63a9eff89bdcfc7c5052bed7?token=357

###
# .findMatriculasEPrefixos
# params: none
GET	http://localhost:3333/acessos/findMatriculasEPrefixos

