###
# .getVideo
# Não são necessários parâmetros
# Não utiliza o isTokenValid, não necessita de concessão de acesso
GET  http://localhost:3333/carrossel/video

# Retorno:
# objeto com as informações do vídeo mais próximo da data atual
# application/json; charset=utf-8
# Exemplo:
# {
#   "id": 92,
#   "urlVideo": "nomeVideo.mp4",
#   "dataInicioReproducao": "29/12/2022 12:00:00",
#   "dataFimReproducao": "2022-12-29T03:00:00.000Z",
#   "matriculaFunci": "F4539214",
#   "nomeFunci": "Izadora Netz Sieczkowski",
#   "ativo": "1",
#   "createdAt": "05/12/2022 11:49:19",
#   "updatedAt": "05/12/2022 11:49:19"
# }


###
# .getVideos
# Acesso necessário: Carrossel de Notícias > CONSULTAR e/ou GERENCIAR
GET http://localhost:3333/carrossel/videos

# Retorno:
# array de objetos ordenados pela maior data do param dataInicioReproducao
# application/json; charset=utf-8
# Exemplo:
# [
#   {
#     "id": 111,
#     "urlVideo": "painelComunicacao/mock3.mp4",
#     "dataInicioReproducao": "28/02/2023 12:00:00",
#     "dataFimReproducao": "2023-01-04T03:00:00.000Z",
#     "matriculaFunci": "F4539214",
#     "nomeFunci": "Izadora Netz Sieczkowski",
#     "ativo": "1",
#     "createdAt": "04/01/2023 05:31:15",
#     "updatedAt": "06/01/2023 12:15:20"
#   },
#   {
#     "id": 110,
#     "urlVideo": "painelComunicacao/mock2.mp4",
#     "dataInicioReproducao": "23/01/2023 12:00:00",
#     "dataFimReproducao": "2023-01-31T03:00:00.000Z",
#     "matriculaFunci": "F4539214",
#     "nomeFunci": "Izadora Netz Sieczkowski",
#     "ativo": "1",
#     "createdAt": "04/01/2023 05:30:23",
#     "updatedAt": "05/01/2023 04:44:48"
#   },
# (...)

###
# .postVideo
# params: dataInicioReproducao, file
# Acesso necessário: Carrossel de Notícias > GERENCIAR
# Renomear arquivo para testar caso apresente retorno "Já existe um arquivo com este nome" 

POST http://localhost:3333/carrossel/postVideo
Content-Type: multipart/form-data; boundary=abc

--abc
Content-Disposition: form-data; name="file"; filename="mock.mp4"
Content-Type: video/mp4

../Commons/Carrossel/__mocks__/mock.mp4
--abc
Content-Disposition: form-data; name="dataInicioReproducao"

Fri Dec 30 2022 11:03:39 GMT-0300
--abc--


###
# .deleteVideo
# params: id
# Acesso necessário: Carrossel de Notícias > GERENCIAR
# altera o parâmetro "ativo" de "1" para "0". 

POST http://localhost:3333/carrossel/deleteVideo 
content-type: application/json

{ "id" : "80" }

# Exemplo:
# {
#   "id": 80,
#   "urlVideo": "assets/files/pages/painelComunicacao/10OUT.mp4",
#   "dataInicioReproducao": "19/06/2023 12:00:00",
#   "dataFimReproducao": "2022-10-24T03:00:00.000Z",
#   "matriculaFunci": "F0000000",
#   "nomeFunci": "Nome Sobrenome",
#   "ativo": "0",
#   "createdAt": "24/10/2022 04:12:27",
#   "updatedAt": "04/01/2023 02:23:44"
# }


###
# .updateVideo
# params: id, novaDataInicioReproducao
# Acesso necessário: Carrossel de Notícias > GERENCIAR
POST http://localhost:3333/carrossel/updateVideo 
content-type: application/json

{ "id" : "62", "novaDataInicioReproducao": "2023-02-04" }

# Exemplo
# {
#   "id": 62,
#   "urlVideo": "video.mp4",
#   "dataInicioReproducao": "04/02/2023 12:00:00",
#   "dataFimReproducao": "2022-10-20T03:00:00.000Z",
#   "matriculaFunci": "F0000000",
#   "nomeFunci": "Nome Sobrenome",
#   "ativo": "0",
#   "createdAt": "20/10/2022 04:19:03",
#   "updatedAt": "04/01/2023 03:06:29"
# }