###
# .find
# params: idMtn, token
# necessário usuário estar logado (token)
POST http://localhost:3333/mtn/adm/analisar/34615?token=123
Content-Type: text/plain; charset=utf-8
# Retorno

###
# .novaNotaInterna
# params: token, notaInterna
# necessário usuário estar logado (token)
POST http://localhost:3333/mtn/adm/nova-nota?token=123
Content-Type: application/json

{"notaInterna":{"desc_nota":"Teste de anotação interna.", "idEnvolvido":7363}}

# Retorno
# Booleano que iforma se a inclusão foi bem sucedida
# Content-Type: text/plain; charset=utf-8
# Exemplo
# true

###
# .getNotasByEnvolvido
# params: token, idEnvolvido, idMtn
# necessário usuário estar logado (token)
GET	http://localhost:3333/mtn/adm/notas-internas?token=123&idEnvolvido=7363

# Retorno
# array com a lista de notas do envolvido indicado
# Content-Type: application/json; charset=utf-8
# Exemplo
# [
#   {
#     "id": 1,
#     "id_envolvido": 7363,
#     "mat_resp_acao": "F3283371",
#     "nome_resp_acao": "Fernando Vieira da Silva",
#     "prefixo_resp_acao": "9009",
#     "nome_prefixo_resp_acao": "SUPER ADM",
#     "desc_nota": "teste",
#     "created_at": "05/12/2022 10:55:19",
#     "updated_at": "05/12/2022 10:55:19"
#   },
# ]

###
# .registrarLeituraNotaInterna
# params: token, idEnvolvido, idNotaInterna
# necessário usuário estar logado (token)
POST http://localhost:3333/mtn/adm/leitura-nota?token=123
Content-Type: application/json

{"leituraNota":{"idEnvolvido":10281,"idNotaInterna":7}}

# Retorno
# Array com as notas já lidas
# Content-Type: application/json; charset=utf-8
# Exemplo
# [
# 	{
# 		"id": 32,
# 		"id_envolvido": 7363,
# 		"prefixo_leitura": "9009",
# 		"nome_prefixo_leitura": "SUPER ADM",
# 		"data_leitura": "14/12/2022 14:48:11",
# 		"mat_leitura": "F3283371",
# 		"nome_leitura": "Fernando Vieira da Silva",
# 		"id_nota_interna": 1,
# 		"created_at": "14/12/2022 14:48:11",
# 		"updated_at": "14/12/2022 14:48:11"
# 	},
# 	...
# ]



###