module.exports = {
  caminhoModels: "App/Models/Mysql/Tarifas",
  PATH_ANEXOS_PAGAMENTOS: "tarifas/comprovantes_pagamento",
  ESPECIE: "Espécie",
  CONTA_CORRENTE: "Conta Corrente",
  TIPO_PROPRIO: "proprio",
  TIPO_RECADO: "recado",
  ACAO_RESERVA: "reservou para pagamento",
  ACAO_REGISTRO_PGTO: "registrou pagamento",
  ACAO_CONFIRMA_REGISTRO_PGTO: "confirmou comprovante de pagamento",
  ACAO_CANCELOU_REGISTRO_PGTO: "cancelou registro de pagamento",
  ACAO_CANCELOU_RESERVA: "cancelou reserva de pagamento",
  STATUS_RESERVADA: 1,
  STATUS_PENDENTE_RESERVA: 2,
  STATUS_PGTO_REGISTRADO: 3,
  STATUS_FINALIZADO: 4,
  STATUS: [
    this.STATUS_RESERVADA,
    this.STATUS_PENDENTE_RESERVA,
    this.STATUS_PGTO_REGISTRADO,
    this.STATUS_FINALIZADO,
  ],
  ACOES: [
    this.ACAO_RESERVA,
    this.ACAO_REGISTRO_PGTO,
    this.ACAO_CONFIRMA_REGISTRO_PGTO,
    this.ACAO_CANCELOU_REGISTRO_PGTO,
  ],
};
