const Historicos = {
  NOVA_SOLICITACAO: 0,
  FUNCI_PARECER: 1,
  FUNCI_DEACORDO: 2,
  SOLICITACAO_ENCAMINHADA_SUPERADM: 3,
  SOLICITACAO_ENCAMINHADA_DIPES_GEPES: 4,
  SOLICITACAO_ENCAMINHADA_OUTRA_UNIDADE: 5,
  SOLICITACAO_CANCELADA: 6,
  SOLICITACAO_CONFIRMADA: 7,
  SOLICITACAO_NEGADA: 8
}

module.exports = Historicos;