module.exports = {
  NOME_FERRAMENTA: 'Designação Interina',
  TIPOS: {
    DESIGNACAO: 1,
    ADICAO: 2
  },
  PREFIXO_SUPERADM: '9009',
  PREFIXO_DIVAR: '8592',
  PREFIXO_DIRAV: '9220',
  PREFIXO_DIPES: '8559',
  PREFIXO_GEPES: '8929',
  PREFIXO_VIVAR: '8166',
  PREFIXO_GENERICO: '0000',
  UOR_SUPERADM: 456778,
  UOR_VIVAR: 18525,
  UOR_STRING_SUPERADM: '000456778',
  UOR_STRING_VIVAR: '000018525',
  UOR_DIVAR: 18948,
  UOR_DIRAV: 464251,
  THREAD_COUNT: 50,
  CARGOS_SUPERINTENDENTES: [
    'SUPERINTENDENTE UT',
    'SUPER REGIONAL UT',
    'SUPERINTENDENTE',
    'SUPERINTENDENTE REG'
  ],
  CARGOS_GERENTE_GERAL: 'GER GERAL UN',
  PARECER: {
    GG_ORIG: 'parecer_origem',
    COMITE_ORIG: 'parecer_origem',
    GG_DEST: 'parecer_destino',
    COMITE_DEST: 'parecer_destino',
    FUNCI_SUPERADM: 'funci_superadm',
    FUNCI_DIPES: 'parecer_dipes',
    FUNCI_GEPES: 'parecer_gepes',
    FUNCI_DIVAR: 'parecer_diretoria',
    FUNCI_DIRAV: 'parecer_diretoria',
    COMITE_SUPER_ORIGEM: 'parecer_super_origem',
    SUPER_REGIONAL_ORIGEM: 'parecer_super_origem',
    SUPER_ESTADUAL_ORIGEM: 'parecer_superintendente_origem',
    COMITE_SUPER_DESTINO: 'parecer_super_destino',
    SUPER_REGIONAL_DESTINO: 'parecer_super_destino',
    SUPER_ESTADUAL_DESTINO: 'parecer_superintendente_destino',
  },
  ANALISE: {
    gg_orig: 'parecer_origem',
    comite_orig: 'parecer_origem',
    gg_dest: 'parecer_destino',
    comite_dest: 'parecer_destino',
    funci_superadm: 'funci_superadm',
    funci_dipes: 'parecer_dipes',
    funci_gepes: 'parecer_gepes',
    funci_divar: 'parecer_diretoria',
    funci_dirav: 'parecer_diretoria',
    comite_super_origem: 'parecer_super_origem',
    super_regional_origem: 'parecer_super_origem',
    super_estadual_origem: 'parecer_super_origem',
    comite_super_destino: 'parecer_super_destino',
    super_regional_destino: 'parecer_super_destino',
    super_estadual_destino: 'parecer_super_destino',
    comite_diretoria: 'parecer_diretoria',
  },
  PERFIL: {
    GG_ORIG: 'gg_orig',
    FUNCI_ORIG: 'funci_orig',
    COMITE_ORIG: 'comite_orig',
    GG_DEST: 'gg_dest',
    FUNCI_DEST: 'funci_dest',
    COMITE_DEST: 'comite_dest',
    FUNCI_SUPER_ORIG: 'funci_super_orig',
    FUNCI_GEREV_ORIG: 'funci_gerev_orig',
    FUNCI_SUPER_DEST: 'funci_super_dest',
    FUNCI_GEREV_DEST: 'funci_gerev_dest',
    FUNCI_SUPERADM: 'funci_superadm',
    FUNCI_DIPES: 'funci_dipes',
    FUNCI_GEPES: 'funci_gepes',
    FUNCI_DIVAR: 'funci_divar',
    FUNCI_DIRAV: 'funci_dirav',
    COMITE_SUPER_ORIGEM: 'comite_super_origem',
    SUPER_REGIONAL_ORIGEM: 'super_regional_origem',
    SUPER_ESTADUAL_ORIGEM: 'super_estadual_origem',
    COMITE_SUPER_DESTINO: 'comite_super_destino',
    SUPER_REGIONAL_DESTINO: 'super_regional_destino',
    SUPER_ESTADUAL_DESTINO: 'super_estadual_destino',
    COMITE_DIRETORIA: 'comite_diretoria',
  },
  PERFIS_EQUIV: {
    GG_ORIG: [
      "GG_ORIG"
    ],
    GG_DEST: [
      "GG_DEST"
    ],
    SUPERIOR: [
      "COMITE_SUPER_DESTINO",
      "SUPER_REGIONAL_DESTINO",
      "SUPER_ESTADUAL_DESTINO",
    ]
  },
  PERFIS_GETPENDENCIAS: {
    gg_orig: "gg_orig",
    gg_dest: "gg_dest",
    super_regional_destino: "super_regional_destino",
    super_estadual_destino: "super_estadual_destino",
    funci_superadm: "funci_superadm",
    funci_dipes: "funci_dipes",
    funci_gepes: "funci_gepes",
    funci_divar: "funci_divar",
    funci_dirav: "funci_dirav",
  },

  DATABASE_DATETIME_INPUT: 'YYYY-MM-DD HH:mm:ss',
  DATABASE_DATETIME_OUTPUT: 'DD/MM/YYYY HH:mm:ss',
  DATABASE_DATE_INPUT: 'YYYY-MM-DD',
  DATABASE_DATE_OUTPUT: 'DD/MM/YYYY',
  CODIGOS_PRIORIZADOS: [
    '200', '201', '222', '224', '225', '226', '227', '228', '232', '233', '235', '236',
    '237', '238', '239', '302', '303', '304', '321', '330', '331', '332', '333', '334',
    '335', '336', '337', '339', '340', '360', '361', '362', '363', '461', '462', '481',
    '482', '483', '600', '601', '603', '604', '605', '610', '615', '620', '800', '850',
  ],
  CODIGOS_PRIORIZADOS_INT: [
    200, 201, 222, 224, 225, 226, 227, 228, 232, 233, 235, 236, 237, 238, 239, 302, 303, 304, 321, 330, 331, 332, 333, 334,
    335, 336, 337, 339, 340, 360, 361, 362, 363, 461, 462, 481, 482, 483, 600, 601, 603, 604, 605, 610, 615, 620, 800, 850
  ],
  TIP_DEP: {
    SUPER_REGIONAL: 3,
    SUPER_ESTADUAL: 4,
    AGENCIA: 13,
    PAA: 15,
    ESTILO: 35,
    POSTO: 44,
    ESCRITORIO: 65,
  },
  SITUACOES: {
    DE_ACORDO_PENDENTE: 1,
    ANALISE_DIPES: 3,
    ANALISE_DIVAR: 4,
    CONCLUIDO: 5,
    CANCELADO: 6,
    ANALISE_OUTRA: 7,
    ANALISE_GEPES: 8,
    ANALISE_UAV: 9,
    ANALISE_SUPERADM: 2,
    ANALISE_URV: 10
  },
  STATUS: {
    SOLICITADO: 1,
    AUTORIZADO: 2,
    NAO_AUTORIZADO: 3,
    EXECUTADO: 4
  },
  ATIVO: 1,
  INATIVO: 0,
  NEGATIVADO: {
    SIM: 1,
    NAO: null
  },
  NIVEL_ALFAB: {
    1: 'A',
    2: 'B',
    3: 'C',
    4: 'D',
    5: 'E',
    6: 'F',
  },
  BD: {
    SIM: 1,
    NAO: 0
  },
  BD_TXT: {
    SIM: "SIM",
    NAO: "NÃO"
  },
  LISTA_CPA: {
    571: "CPA-20",
    101110: "CPA-20",
    572: "CPA-10",
    101109: "CPA-10",
    6784: "CEA",
    4160: "CEA"
  },
  CODIGOS_CPA: [
    "CPA-10",
    "CPA-20"
  ],
  TABELAS: {
    COD_AUSENCIA: 'cod_ausencia',
    SOLICITACOES: 'solicitacoes',
    ANALISES: 'analises',
    CADEIAS: 'cadeias',
    DOCUMENTOS: 'documentos',
    HISTORICOS: 'historicos',
    LIMITROFES: 'limitrofes',
    MAIL_LOG: 'mail_log',
    NEGATIVAS: 'negativas',
    OPTS_BASICAS: 'opts_basicas',
    PREFIXOS_TESTE: 'prefixos_teste',
    SITUACOES: 'situacoes',
    STATUS: 'status',
    TEMPLATES: 'templates',
    TIPOS: 'tipos',
    TIPOS_HISTORICO: 'tipos_historico',
  },
  CODS_AUSENCIA: {
    EXTERIOR: '535',
  },
  LIMITROFES: {
    SIM: 0,
    NAO: 1
  },
  NIVEL_GER: {
    G1UN: '1GUN',
    G1UT: '1GUT',
    G2UT: '2GUT',
    G3UN: '3GUN',
    G1UA: '1GUA',
    G1UE: '1GUE',
    G1UE: '2GUE',
  },
  TIPOS_EMAIL: {
    SOLICITACAO: 1,
    ENCAMINHADA: 2,
    CONCLUIDA: 3,
    CANCELADA: 4
  },
  EMAIL_SUPER_PESSOAS: 'superadm.pessoas@bb.com.br',
  MENSAGEM: {
    SUCESSO: 'SUCESSO',
    FALHA: 'FALHA NO ENVIO',
    NAO_OBRIGATORIO: 'Não Obrigatório'
  },
  NEGATIVAS: {
    LIMITROFES: 'limitrofes',
    CERTS: 'certs',
    POSSE: 'posse',
    INCORPORADO: 'incorporado',
    NOMEACAO: 'nomeacao',
    ODI: 'odi',
    INAMOVIVEL: 'inamovivel',
    VCP: 'vcp',
    HABITUALIDADE: 'habitualidade',
    TRILHAETICA: 'trilhaEtica',
  },
  IDS_NEGATIVAS: {
    LIMITROFES: 1,
    CERTS: 2,
    POSSE: 3,
    INCORPORADO: 4,
    NOMEACAO: 5,
    ODI: 6,
    INAMOVIVEL: 7,
    VCP: 8,
    HABITUALIDADE: 9,
    TRILHAETICA: 10,
  },
  TIPOS_HISTORICO: {
    INCLUSAO: 1,
    ORIGEM: 2,
    DESTINO: 3,
    SUPER_DESTINO: 5,
    SUPERADM: 20,
    CONCLUIDO: 26,
    NEGADO: 27,
    CANCELADO: 28,
    RESPONSAVEL: 29,
    GRAVADO: 30,
    CADEIA: 31,
    SUPER_EST_DESTINO: 32,
    COM_SUPER_DESTINO: 33,
    DIRETORIA_DESTINO: 34,
  },
  TIPOS_PERFIS_DEACORDO: {
    gestorOrigem: ['gg_orig'],
    gestorDestino: ['gg_dest'],
    gestorOrigemDestino: ['gg_orig', 'gg_dest'],
    superior: ['comite_diretoria', 'comite_super_destino', 'super_estadual_destino', 'super_regional_destino'],
  },
  GG_LOJABB: '17103',
  MATRICULA_GENERICA: 'F0000000',
  ABAS: {
    DEACORDO: 1,
    ANALISE_OUTROS: 2,
    ANALISE_PREFIXO: 3,
    MINHAS_PENDENCIAS: 4
  },
  TIPOS_ACESSO: {
    SUPERADM: "SUPERADM",
    DIPES: "DIPES",
    DIVAR: "DIVAR",
    DIRAV: "DIRAV",
    GEPES: "GEPES",
    AGENCIAS: "AGENCIAS",
    OUTROS: "OUTROS",
    REGISTRO: "REGISTRO",
    ACESSO_TESTE: "ACESSO_TESTE",
  },
  OPCOES_BASICAS: {
    AUSPROG06: 1,
    AUSPROG10: 2,
    AUSEPAVAS: 3,
    VACPOSS06: 4,
    LICSAUD07: 5,
    PREF1G3UN: 6,
    LICSAUD60: 7,
    APURDISCP: 8,
    SEMLATERA: 9,
    VAC06G2UT: 10,
    AUSNPRO06: 11,
    AUSNPRO10: 12,
    VAC06G3UN: 13,
    LOBB1G1UN: 14,
  },
  ITENS_OPTS_BASICAS: {
    QTDE_MAX_FUNCI_G3UN_AUS_LIC_SAU_60: 7,
    QTDE_MAX_FUNCI_G3UN_DESIGNACAO: 1,
  },
  TIPOS_DEACORDO: {
    NEGADO: 'negado',
    SUPERIOR: 'superior',
    ORIGEM: 'gestorOrigem',
    DESTINO: 'gestorDestino',
    ORIGEM_DESTINO: 'gestorOrigemDestino',
  },
  CARGO_ESCRITURARIO: '00610',
  COMISSAO_ESCRITURARIO: '00000',
}