export default {
  TOGGLE_SIDEBAR: 'TOGGLE_SIDEBAR',
  TOGGLE_FULLSCREEN: 'TOGGLE_FULLSCREEN',
  AUTH_STATE_CHANGE: 'AUTH_STATE_CHANGE',
  UPDATE_PERMISSIONS: 'UPDATE_PERMISSIONS',
  UPDATE_APPS_STATUS: 'UPDATE_APPS_STATUS',
  RELOAD_USER_PERMISSIONS: 'RELOAD_USER_PERMISSIONS',
};
