module.exports = {
  getPublicoAlvo: require("./getPublicoAlvo.js"),
  ReservarOcorrencia: require("./ReservarOcorrencia.js"),
  GetOneOcorrencia: require("./GetOneOcorrencia"),
  GetReservasPendentesPgtoEspecie: require("./GetReservasPendentesPgtoEspecie"),
  RegistrarPagamento: require("./RegistrarPagamento"),
  GetReservasPendentesPgtoConta: require("./GetReservasPendentesPgtoConta"),
  GetPermissaoPgtoConta: require("./GetPermissaoPgtoConta"),
  GetPagamentosPendentesConfirmacao: require("./GetPagamentosPendentesConfirmacao"),
  checaIsPgtoConta: require("./IsPgtoConta"),
  ConfirmarPagamento: require("./ConfirmarPagamento"),
  isPgtoConfirmado: require("./IsPgtoConfirmado"),
  ChecaPodeConfirmarPgto: require("./ChecaPodeConfirmarPgto"),
  CancelarPagamento: require("./CancelarPagamento"),
  GetReservasFinalizadas: require("./GetReservasFinalizadas"),
  CancelarReserva: require("./CancelarReserva"),
};
