export const mockOutorgante = [
  {
    idProcuracao: 5,
    idSubsidiaria: 1,
    direto: 0,
    procuracao: {
      id: 5,
      idCartorio: 1,
      idOutorgadoSnapshot: 5,
      folha: '45',
      livro: '42',
      dataEmissao: '2022-05-23T03:00:00.000Z',
      dataVencimento: null,
      urlDocumento: 'teste5',
      createdAt: '23/05/2022 13:17',
      updatedAt: '20/07/2022 15:01',
      ativo: 1,
      outorgadoSnapshot: {
        id: 5,
        matricula: 'f1690528',
        cpf: null,
        rg: null,
        nome: 'Bruno Noriller',
        estadoCivil: null,
        cargoCodigo: null,
        cargoNome: null,
        lotacaoCodigo: null,
        lotacaoNome: null,
        lotacaoMunicipio: null,
        lotacaoUf: null,
        createdAt: null,
        updatedAt: null
      },
      cartorio: {
        id: 1,
        cnpj: '00.000.000/0000-00',
        nome: '1º Tabelionato da Vila Bonita',
        cep: '00000-00',
        endereco: 'Beltrano da Siva',
        complemento: '3º Andar',
        bairro: 'Verdes Campos',
        municipio: 'Cidade',
        uf: 'DF',
        createdAt: '24/03/2022 15:55',
        updatedAt: '24/03/2022 15:55',
        ativo: 1
      }
    },
    dadosSubsidiaria: {
      id: 1,
      cnpj: '31591399000156',
      nomeReduzido: 'BB CARTOES',
      nome: 'BB ADMINISTRADORA DE CARTOES DE CREDITO S.A.',
      cep: '70040912',
      endereco: 'SETOR DE AUTARQUIAS NORTE QUADRA 5 LOTE B',
      complemento: 'TORRE I - 2º ANDAR EDIFICIO BANCO DO BRASIL',
      bairro: 'ASA NORTE',
      municipio: 'BRASILIA',
      uf: 'DF',
      createdAt: '08/04/2022 14:30',
      updatedAt: '08/04/2022 14:31',
      ativo: 1
    }
  },
  {
    idProcuracao: 5,
    idSubsidiaria: 2,
    direto: 0,
    procuracao: {
      id: 5,
      idCartorio: 1,
      idOutorgadoSnapshot: 5,
      folha: '45',
      livro: '42',
      dataEmissao: '2022-05-23T03:00:00.000Z',
      dataVencimento: null,
      urlDocumento: 'teste5',
      createdAt: '23/05/2022 13:17',
      updatedAt: '20/07/2022 15:01',
      ativo: 1,
      outorgadoSnapshot: {
        id: 5,
        matricula: 'f1690528',
        cpf: null,
        rg: null,
        nome: 'Bruno Noriller',
        estadoCivil: null,
        cargoCodigo: null,
        cargoNome: null,
        lotacaoCodigo: null,
        lotacaoNome: null,
        lotacaoMunicipio: null,
        lotacaoUf: null,
        createdAt: null,
        updatedAt: null
      },
      cartorio: {
        id: 1,
        cnpj: '00.000.000/0000-00',
        nome: '1º Tabelionato da Vila Bonita',
        cep: '00000-00',
        endereco: 'Beltrano da Siva',
        complemento: '3º Andar',
        bairro: 'Verdes Campos',
        municipio: 'Cidade',
        uf: 'DF',
        createdAt: '24/03/2022 15:55',
        updatedAt: '24/03/2022 15:55',
        ativo: 1
      }
    },
    dadosSubsidiaria: {
      id: 2,
      cnpj: '24933830000130',
      nomeReduzido: 'BB INVESTIMENTO',
      nome: 'BB BANCO DE INVESTIMENTO S.A.',
      cep: '20031923',
      endereco: 'RUA SENADOR DANTAS 105',
      complemento: 'SALA 3701',
      bairro: 'CENTRO',
      municipio: 'RIO DE JANEIRO',
      uf: 'RJ',
      createdAt: '08/04/2022 14:30',
      updatedAt: '08/04/2022 14:31',
      ativo: 1
    }
  },
  {
    idProcuracao: 5,
    idSubsidiaria: 3,
    direto: 0,
    procuracao: {
      id: 5,
      idCartorio: 1,
      idOutorgadoSnapshot: 5,
      folha: '45',
      livro: '42',
      dataEmissao: '2022-05-23T03:00:00.000Z',
      dataVencimento: null,
      urlDocumento: 'teste5',
      createdAt: '23/05/2022 13:17',
      updatedAt: '20/07/2022 15:01',
      ativo: 1,
      outorgadoSnapshot: {
        id: 5,
        matricula: 'f1690528',
        cpf: null,
        rg: null,
        nome: 'Bruno Noriller',
        estadoCivil: null,
        cargoCodigo: null,
        cargoNome: null,
        lotacaoCodigo: null,
        lotacaoNome: null,
        lotacaoMunicipio: null,
        lotacaoUf: null,
        createdAt: null,
        updatedAt: null
      },
      cartorio: {
        id: 1,
        cnpj: '00.000.000/0000-00',
        nome: '1º Tabelionato da Vila Bonita',
        cep: '00000-00',
        endereco: 'Beltrano da Siva',
        complemento: '3º Andar',
        bairro: 'Verdes Campos',
        municipio: 'Cidade',
        uf: 'DF',
        createdAt: '24/03/2022 15:55',
        updatedAt: '24/03/2022 15:55',
        ativo: 1
      }
    },
    dadosSubsidiaria: {
      id: 3,
      cnpj: '04740876000125',
      nomeReduzido: 'CBSS',
      nome: 'COMPANHIA BRASILEIRA DE SOLUCOES E SERVICOS',
      cep: '06455030',
      endereco: 'ALAMEDA XINGU 512',
      complemento: 'ANDAR 3 E 4 EDIFICIO CONDOMINIO EVOLUTION CORPORATE',
      bairro: 'ALPHAVILLE',
      municipio: 'BARUERI',
      uf: 'SP',
      createdAt: '08/04/2022 14:30',
      updatedAt: '08/04/2022 14:31',
      ativo: 1
    }
  }
];
