const { getComposicaoComite,
        getListaComites,
        getDadosComite,
        getListaComitesByMatricula
      } = use("App/Commons/Arh/dadosComites");

module.exports = {
    getManyDependencias: use("App/Commons/Arh/getManyDependencias"),
    getMatchedDependencias: use("App/Commons/Arh/getMatchedDependencias"),
    getManyFuncis: use("App/Commons/Arh/getManyFuncis"),
    getMatchedFuncis: use("App/Commons/Arh/getMatchedFuncis"),
    getMatchedFuncisLotados: use("App/Commons/Arh/getMatchedFuncisLotados"),
    getOneDependencia: use("App/Commons/Arh/getOneDependencia"),
    getOneDependenciaByUor: use("App/Commons/Arh/getOneDependenciaByUor"),
    getOneFunci: use("App/Commons/Arh/getOneFunci"),
    getOneFunciAdm: use("App/Commons/Arh/getOneFunciAdm"),
    pretifyDependencia: use("App/Commons/Arh/pretifyDependencia"),
    pretifyFunci: use("App/Commons/Arh/pretifyFunci"),
    getComposicaoComite,
    getListaComites,
    getDadosComite,
    getListaComitesByMatricula,
    getFuncisByPrefixo: use("App/Commons/Arh/getFuncisByPrefixo"),
    getComitesAdmByMatricula: use("App/Commons/Arh/getComitesAdmByMatricula"),
    getFuncisByNomeCargo: use("App/Commons/Arh/getFuncisByNomeCargo"),
    isComissaoNivelGerencial: use("App/Commons/Arh/isComissaoNivelGerencial"),
    getDotacaoDependencia: use("App/Commons/Arh/getDotacaoDependencia"),
    getCursosEtica: use("App/Commons/Arh/getCursosEtica"),
    getTreinamentosFunci: use("App/Commons/Arh/getTreinamentosFunci"),
    isFunciIncorporado: use("App/Commons/Arh/isFunciIncorporado"),
    isNomeacaoPendente: use("App/Commons/Arh/isNomeacaoPendente"),
    getLatLong: use("App/Commons/Arh/getLatLong"),
    getRotaRodoviaria: use("App/Commons/Arh/getRotaRodoviaria"),
    getCPAFunci: use("App/Commons/Arh/getCPAFunci"),
    getCPAFuncao: use("App/Commons/Arh/getCPAFuncao"),
    getDepESubord: use('App/Commons/Arh/getDepESubord'),
    isAdmin: use('App/Commons/Arh/isAdmin'),
    isPrefixoUN: use('App/Commons/Arh/isPrefixoUN'),
    isPrefixoUT: use('App/Commons/Arh/isPrefixoUT'),
    isFunciPlataforma: use("App/Commons/Arh/getFuncisPlataforma"),
    getDadosComissao: use("App/Commons/Arh/getDadosComissao"),
    getDadosComissaoCompleto: use("App/Commons/Arh/getDadosComissaoCompleto"),
    getVinculoGerev: use("App/Commons/Arh/getVinculoGerev"),
    isUsuarioPrefixoGerev: use("App/Commons/Arh/isUsuarioPrefixoGerev"),
    getFunciByCPF: use("App/Commons/Arh/getFunciByCPF"),
}