# PesquisaController.pesquisaProcuracao
# body: pesquisa
# pesquisa pode ser uma matricula, nome ou prefixo
POST http://localhost:3333/procuracoes/pesquisa
content-type: application/json

{
  "pesquisa": "9009"
}

# salvo procurando com a pesquisa "9009" que vai retornar as procuracoes do prefixo 9009
# a primeira procuração já retorna com a cadeia de procuracoes
# o retorno é sempre um array, que pode ser um array vazio

# Exemplo de retorno
# [
#   {
#     "idProcuracao": null,
#     "idProxy": "2fb9cb1f-f132-4445-8605-f4c9c73e8a1e",
#     "matricula": "F8718628",
#     "nome": "ROGERIO NATAL CERRI                     ",
#     "cargoNome": "SUPERINTENDENTE UT            ",
#     "prefixo": "9009",
#     "ativo": 1,
#     "prefixo_lotacao": "9009",
#     "cpf": "21449814859",
#     "dataNasc": "1979-07-09T03:00:00.000Z",
#     "estadoCivil": "2",
#     "rg": "29135015X - SSP - SP    ",
#     "municipio": "BRASILIA",
#     "uf": "DF",
#     "endereco": "Endereço: SAUN QUADRA 5, BLOCO B, TORRE NORTE - Complemento: ED. BANCO DO BRASIL, ASA NORTE-DF,  - Bairro: A NORTE - CEP: 70040912",
#     "procuracao": [
#       **cadeia de procuracoes**
#     ]
#   },
# ]

###

# Sobre o PesquisaController.getProcuracao
# Aceita um de idProxy ou idProcuracao
# Throw erro se não enviar nenhum ou enviar dois
# O retorno é sempre um array, que pode ser vazio
# O primeiro elemento é a procuracao que está procurando
# Cada elemento seguinte é a procuracao pai da anterior

###

# PesquisaController.getProcuracao
# params: idProxy OU idProcuracao
# exemplo usando id invalido
GET http://localhost:3333/procuracoes/pesquisa?idProcuracao=-1

# retorna []

###

# PesquisaController.getProcuracao
# params: idProxy OU idProcuracao
# exemplo passando nenhum
GET http://localhost:3333/procuracoes/pesquisa

# ID não pode ser vazio

###

# PesquisaController.getProcuracao
# params: idProxy OU idProcuracao
# exemplo passando os dois
GET http://localhost:3333/procuracoes/pesquisa?idProcuracao=6&idProxy=2fb9cb1f-f132-4445-8605-f4c9c73e8a1e

# Preencha apenas um dos ID

###

# PesquisaController.getProcuracao
# params: idProxy OU idProcuracao
# exemplo usando idProxy
GET http://localhost:3333/procuracoes/pesquisa?idProxy=2fb9cb1f-f132-4445-8605-f4c9c73e8a1e

# Exemplo de retorno
# [
#   {
#     "procuracaoAgregada": null,
#     "outorgado": {
#       "matricula": "F8718628",
#       "nome": "ROGERIO NATAL CERRI",
#       "cargo": "SUPERINTENDENTE UT",
#       "prefixo": "9009",
#       "cpf": "21449814859",
#       "rg": "29135015X - SSP - SP",
#       "estadoCivil": "CASADO(A)",
#       "municipio": "BRASILIA",
#       "uf": "DF",
#       "endereco": "endereço"
#     },
#     "subsidiarias": [
#       {
#         "id": 3,
#         "nome": "BB CONSÓRCIOS",
#         "nome_completo": "BB ADMINISTRADORA DE CONSÓRCIOS S.A.",
#         "cnpj": "06.043.050/0001-32",
#         "subAtivo": 1,
#         "procuracaoId": 2,
#         "procuracaoAtiva": 1,
#         "emissao": "2021-02-25",
#         "vencimento": "2023-12-10",
#         "manifesto": "2022-11-07",
#         "folha": "039 e 040",
#         "livro": "3087",
#         "doc": "https://desenv01adm.intranet.bb.com.br/server-api-procuracao//procuracoes/cadastro/download-arquivo/59440782-85dc-47b9-96d6-b2b9644d1415.pdf",
#         "cartorio": "CARTÓRIO DO 5º OFÍCIO DE NOTAS DE TAGUATINGA-DF"
#       },
#       {
#         "id": 2,
#         "nome": "BB CARTÕES",
#         "nome_completo": "BB ADMINISTRADORA DE CARTÕES DE CRÉDITO S.A.",
#         "cnpj": "31.591.399/0001-56",
#         "subAtivo": 1,
#         "procuracaoId": 4,
#         "procuracaoAtiva": 1,
#         "emissao": "2021-02-05",
#         "vencimento": "2023-02-07",
#         "manifesto": "2022-11-07",
#         "folha": "167",
#         "livro": "3345",
#         "doc": "https://desenv01adm.intranet.bb.com.br/server-api-procuracao//procuracoes/cadastro/download-arquivo/340404e2-d31d-44ab-b630-4d1b302da66a.pdf",
#         "cartorio": "CARTÓRIO DO 5º OFÍCIO DE NOTAS DE TAGUATINGA-DF"
#       },
#       {
#         "id": 1,
#         "nome": "BB",
#         "nome_completo": "BANCO DO BRASIL S.A.",
#         "cnpj": "00.000.000/0001-91",
#         "subAtivo": 1,
#         "procuracaoId": 13,
#         "procuracaoAtiva": 1,
#         "emissao": "2022-08-23",
#         "vencimento": "2022-09-02",
#         "manifesto": "2022-08-22",
#         "folha": "42",
#         "livro": "42",
#         "doc": "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
#         "cartorio": "CARTÓRIO DO 3º OFÍCIO DE NOTAS E PROTESTO DE TÍTULOS DE BRASÍLIA"
#       }
#     ]
#   }
# ]

###

# PesquisaController.getProcuracao
# params: idProxy OU idProcuracao
# exemplo usando idProcuracao
GET http://localhost:3333/procuracoes/pesquisa?idProcuracao=6

# Exemplo de Retorno
# [
#   {
#     "procuracaoAgregada": {
#       "procuracaoId": 6,
#       "procuracaoAtiva": 1,
#       "emissao": "2022-11-16",
#       "vencimento": "2022-11-26",
#       "manifesto": null,
#       "folha": null,
#       "livro": null,
#       "doc": "http://127.0.0.1:3333/procuracoes/cadastro/download-arquivo/98d49aa8-e4d2-41bd-a3e2-7394b86ef722.pdf",
#       "cartorio": null
#     },
#     "outorgado": {
#       "matricula": "F2326178",
#       "nome": "DAVIDSON DA ROCHA DE CARVALHO",
#       "cargo": "GER ADMINIST UT",
#       "prefixo": "7400",
#       "cpf": "30192877828",
#       "rg": "33 447 719 0 - SSP - SP",
#       "estadoCivil": "CASADO(A)",
#       "municipio": "SAO PAULO",
#       "uf": "SP",
#       "endereco": "endereço"
#     },
#     "subsidiarias": [
#       {
#         "id": 1,
#         "nome": "BB",
#         "nome_completo": "BANCO DO BRASIL S.A.",
#         "cnpj": "00.000.000/0001-91",
#         "subAtivo": 1
#       },
#       {
#         "id": 2,
#         "nome": "BB CARTÕES",
#         "nome_completo": "BB ADMINISTRADORA DE CARTÕES DE CRÉDITO S.A.",
#         "cnpj": "31.591.399/0001-56",
#         "subAtivo": 1
#       },
#       {
#         "id": 3,
#         "nome": "BB CONSÓRCIOS",
#         "nome_completo": "BB ADMINISTRADORA DE CONSÓRCIOS S.A.",
#         "cnpj": "06.043.050/0001-32",
#         "subAtivo": 1
#       }
#     ]
#   },
#   {
#     "procuracaoAgregada": null,
#     "outorgado": {
#       "matricula": "F8718628",
#       "nome": "ROGERIO NATAL CERRI",
#       "cargo": "SUPERINTENDENTE UT",
#       "prefixo": "9009",
#       "cpf": "21449814859",
#       "rg": "29135015X - SSP - SP",
#       "estadoCivil": "CASADO(A)",
#       "municipio": "BRASILIA",
#       "uf": "DF",
#       "endereco": "endereço"
#     },
#     "subsidiarias": [
#       {
#         "id": 1,
#         "nome": "BB",
#         "nome_completo": "BANCO DO BRASIL S.A.",
#         "cnpj": "00.000.000/0001-91",
#         "subAtivo": 1,
#         "procuracaoId": 1,
#         "procuracaoAtiva": 1,
#         "emissao": "2021-02-05",
#         "vencimento": "2026-02-05",
#         "manifesto": "2022-11-07",
#         "folha": "162 a 165",
#         "livro": "3345",
#         "doc": "https://desenv01adm.intranet.bb.com.br/server-api-procuracao//procuracoes/cadastro/download-arquivo/83b6816f-02fb-4b5c-a8b8-da1ed971db33.pdf",
#         "cartorio": "CARTÓRIO DO 5º OFÍCIO DE NOTAS DE TAGUATINGA-DF"
#       },
#       {
#         "id": 3,
#         "nome": "BB CONSÓRCIOS",
#         "nome_completo": "BB ADMINISTRADORA DE CONSÓRCIOS S.A.",
#         "cnpj": "06.043.050/0001-32",
#         "subAtivo": 1,
#         "procuracaoId": 2,
#         "procuracaoAtiva": 1,
#         "emissao": "2021-02-25",
#         "vencimento": "2023-12-10",
#         "manifesto": "2022-11-07",
#         "folha": "039 e 040",
#         "livro": "3087",
#         "doc": "https://desenv01adm.intranet.bb.com.br/server-api-procuracao//procuracoes/cadastro/download-arquivo/59440782-85dc-47b9-96d6-b2b9644d1415.pdf",
#         "cartorio": "CARTÓRIO DO 5º OFÍCIO DE NOTAS DE TAGUATINGA-DF"
#       },
#       {
#         "id": 2,
#         "nome": "BB CARTÕES",
#         "nome_completo": "BB ADMINISTRADORA DE CARTÕES DE CRÉDITO S.A.",
#         "cnpj": "31.591.399/0001-56",
#         "subAtivo": 1,
#         "procuracaoId": 4,
#         "procuracaoAtiva": 1,
#         "emissao": "2021-02-05",
#         "vencimento": "2023-02-07",
#         "manifesto": "2022-11-07",
#         "folha": "167",
#         "livro": "3345",
#         "doc": "https://desenv01adm.intranet.bb.com.br/server-api-procuracao//procuracoes/cadastro/download-arquivo/340404e2-d31d-44ab-b630-4d1b302da66a.pdf",
#         "cartorio": "CARTÓRIO DO 5º OFÍCIO DE NOTAS DE TAGUATINGA-DF"
#       }
#     ]
#   }
# ]
###
