stages:
  - build

homologacao:
  stage: build
  script:
    - echo "--> Navegar até o diretório do projeto"
    - cd /home/gitlab-runner/projetos-software/node-frontend
    - echo "--> Pull das alterações"
    - git pull
    - git checkout develop
    - echo "--> Executando o build"
    - npm run build
    - echo "--> Build do frontend finalizado"
  only:
    refs:
      - develop
  tags:
    - develop-enviroment-frontend

homologacao_env:
  stage: build
  script:
    - echo "--> Navegar até o diretório do projeto"
    - cd /home/gitlab-runner/projetos-software/develop_environments/$CI_COMMIT_REF_NAME/frontend
    - echo "--> Pull das alterações"
    - git pull
    - git checkout $CI_COMMIT_REF_NAME
    - echo "--> Executando o build"
    - npm run build
    - echo "--> Build do frontend finalizado"
  only:
    refs:
      - /^develop_env_[1-4]$/
  tags:
    - develop-enviroment-frontend
    
producao:
  stage: build
  script:
    - echo "--> Navegar até o diretório do projeto"
    - cd /home/gitlab-runner/projetos-software/node-frontend
    - echo "--> Pull das alterações"
    - git pull
    - git checkout master
    - echo "--> Executando o build"
    - npm run build
    - echo "--> Copiar o build para o diretório do apache"
    - cp -R /home/gitlab-runner/projetos-software/node-frontend/build /srv/www/htdocs/
  only:
    refs:
      - master
  tags:
   - production-node-server
    
