import { FLUXOS_PROCURACAO } from '../../Constants';
import { ETAPA_BAIXAR_MINUTA } from './Etapas/EtapaBaixarMinuta/ETAPA_BAIXAR_MINUTA';
import { ETAPA_BAIXAR_MINUTA_MASSIFICADO } from './Etapas/EtapaBaixarMinutaMassificado/ETAPA_BAIXAR_MINUTA_MASSIFICADO';
import { ETAPA_CARTORIO } from './Etapas/EtapaCartorio/ETAPA_CARTORIO';
import { ETAPA_FINALIZAR_CADASTRO } from './Etapas/EtapaFinalizar/ETAPA_FINALIZAR_CADASTRO';
import { ETAPA_FINALIZAR_MASSIFICADO_MINUTA } from './Etapas/EtapaFinalizar/ETAPA_FINALIZAR_MASSIFICADO_MINUTA';
import { ETAPA_FINALIZAR_MINUTA } from './Etapas/EtapaFinalizar/ETAPA_FINALIZAR_MINUTA';
import { ETAPA_MINUTA } from './Etapas/EtapaMinuta/ETAPA_MINUTA';
import { ETAPA_MINUTA_MASSIFICADO } from './Etapas/EtapaMinutaMassificado/ETAPA_MINUTA_MASSIFICADO';
import { ETAPA_OUTORGADO } from './Etapas/EtapaOutorgado/ETAPA_OUTORGADO';
import { ETAPA_OUTORGADO_MASSIFICADO } from './Etapas/EtapaOutorgadoMassificado/ETAPA_OUTORGADO_MASSIFICADO';
import { ETAPA_OUTORGANTE } from './Etapas/EtapaOutorgante/ETAPA_OUTORGANTE';
import { ETAPA_PROCURACAO_PARTICULAR } from './Etapas/EtapaProcuracaoParticular/ETAPA_PROCURACAO_PARTICULAR';
import { ETAPA_PROCURACAO_PUBLICA } from './Etapas/EtapaProcuracaoPublica/ETAPA_PROCURACAO_PUBLICA';
import { ETAPA_PROCURACAO_SUBSIDIARIA } from './Etapas/EtapaProcuracaoSubsidiaria/ETAPA_PROCURACAO_SUBSIDIARIA';
import { ETAPA_SUBSIDIARIA } from './Etapas/EtapaSubsidiaria/ETAPA_SUBSIDIARIA';

export const FLUXOS_CADASTRO = {
  [FLUXOS_PROCURACAO.PUBLICA]: [
    ETAPA_CARTORIO,
    ETAPA_PROCURACAO_PUBLICA,
    ETAPA_OUTORGADO,
    ETAPA_OUTORGANTE,
    ETAPA_FINALIZAR_CADASTRO,
  ],

  [FLUXOS_PROCURACAO.PARTICULAR]: [
    ETAPA_PROCURACAO_PARTICULAR,
    ETAPA_OUTORGADO,
    ETAPA_OUTORGANTE,
    ETAPA_FINALIZAR_CADASTRO,
  ],

  [FLUXOS_PROCURACAO.SUBSIDIARIA]: [
    ETAPA_CARTORIO,
    ETAPA_PROCURACAO_SUBSIDIARIA,
    ETAPA_OUTORGADO,
    ETAPA_SUBSIDIARIA,
    ETAPA_FINALIZAR_CADASTRO,
  ]
};

export const FLUXOS_CADASTRO_CONTINUE = {
  [FLUXOS_PROCURACAO.PUBLICA]: [
    ETAPA_CARTORIO,
    ETAPA_PROCURACAO_PUBLICA,
    ETAPA_FINALIZAR_CADASTRO,
  ],

  [FLUXOS_PROCURACAO.PARTICULAR]: [
    ETAPA_PROCURACAO_PARTICULAR,
    ETAPA_FINALIZAR_CADASTRO,
  ],
};

export const FLUXOS_MINUTA = {
  [FLUXOS_PROCURACAO.PUBLICA]: [
    ETAPA_OUTORGADO,
    ETAPA_OUTORGANTE,
    ETAPA_MINUTA,
    ETAPA_FINALIZAR_MINUTA,
    ETAPA_BAIXAR_MINUTA,
  ],

  [FLUXOS_PROCURACAO.PARTICULAR]: [
    ETAPA_OUTORGADO,
    ETAPA_OUTORGANTE,
    ETAPA_MINUTA,
    ETAPA_FINALIZAR_MINUTA,
    ETAPA_BAIXAR_MINUTA,
  ],
};

export const FLUXOS_MINUTA_CONTINUE = {
  [FLUXOS_PROCURACAO.PUBLICA]: [
    ETAPA_BAIXAR_MINUTA,
  ],

  [FLUXOS_PROCURACAO.PARTICULAR]: [
    ETAPA_BAIXAR_MINUTA,
  ],
};

export const FLUXOS_MASSIFICADO_MINUTA = {
  [FLUXOS_PROCURACAO.PUBLICA]: [
    ETAPA_OUTORGADO_MASSIFICADO,
    ETAPA_OUTORGANTE,
    ETAPA_MINUTA_MASSIFICADO,
    ETAPA_FINALIZAR_MASSIFICADO_MINUTA,
    ETAPA_BAIXAR_MINUTA_MASSIFICADO,
  ],
};

export const FLUXOS_MASSIFICADO_MINUTA_CONTINUE = {
  [FLUXOS_PROCURACAO.PUBLICA]: [
    ETAPA_BAIXAR_MINUTA_MASSIFICADO,
  ],
};
