export default {
  
  FILTRAR_DEMANDAS : 'FILTRAR_DEMANDAS',
  LIMPAR_PESQUISA: 'LIMPAR_PESQUISA',
  FETCH_DEMANDA: 'FETCH_DEMANDA',
  FETCH_DEMANDAS: 'FETCH_DEMANDAS',
  CREATE_DEMANDA: 'CREATE_DEMANDA',
  EDIT_DEMANDA: 'EDIT_DEMANDA',
  DELETE_DEMANDA: 'DELETE_DEMANDA',
  DUPLICATE_DEMANDA: 'DUPLICATE_DEMANDA',
  SAVE_DEMANDA: 'SALVAR_DEMANDA',
  UPDATE_FORM_DATA: 'UPDATE_FORM_DATA',
  UPDATE_ERROR_MESSAGES: 'UPDATE_ERROR_MESSAGES',
  CLEAR_ERROR_MESSAGES: 'CLEAR_ERROR_MESSAGES',
  FETCH_COLABORADOR: 'FETCH_COLABORADOR',
  FILTRAR_EXPIRADAS: 'FILTRAR_DESATIVADAS',
  ARQUIVAR_DEMANDA: 'ARQUIVAR_DEMANDA',
  FETCH_ESTATISTICAS_DEMANDA: 'FETCH_ESTATISTICAS_DEMANDA',
  FETCH_HISTORICO_NOTIFICACOES: 'FETCH_HISTORICO_NOTIFICACOES',
  FETCH_STATUS_NOTIFICACOES: 'FETCH_STATUS_NOTIFICACOES',
  FETCH_PUBLICO_ALVO: 'FETCH_PUBLICO_ALVO',
  ENVIANDO_LEMBRETES: 'ENVIANDO_LEMBRETES',
  ENVIANDO_CONVITES: 'ENVIANDO_CONVITES',
  //Especifica para a lista de perguntas (frescuragem minha)
  CLEAR_QUESTION_MESSAGES: 'CLEAR_QUESTION_MESSAGES',
  FETCH_RESPOSTA: 'FETCH_RESPOSTA'
}