###
# .getCargosComissoesFot09
# params: token
# necessário usuário estar logado (token) e ter acesso à ferramenta Parâmetros 
GET	http://localhost:3333/movimentacoes/getCargosComissoesFot09?token=123

# Retorno
# JSON com informações dos parâmetros do prefixo do usuario.
# Content-Type: application/json; charset=utf-8
# Exemplo
# 

###
# .getJurisdicoesSubordinadas
# params: token
# necessário usuário estar logado (token) e ter acesso à ferramenta 
GET	http://localhost:3333/movimentacoes/getJurisdicoesSubordinadas?token=123&prefixo=1228

# Retorno
# JSON com as agências jurisdicionadas ao prefixo do usuario.
# Content-Type: application/json; charset=utf-8
# Exemplo
# 

###
# .listaComiteParamAlcadas
# params: token
# necessário usuário estar logado (token) e ter acesso à ferramenta 
GET	http://localhost:3333/movimentacoes/listaComiteParamAlcadas?token=123&prefixo=9009

# Retorno
# JSON com as agências jurisdicionadas ao prefixo do usuario.
# Content-Type: application/json; charset=utf-8
# Exemplo
# 

###
# .getPrefixoBySubordinada
# params: token
# necessário usuário estar logado (token) e ter acesso à ferramenta 
GET	http://localhost:3333/movimentacoes/getPrefixoBySubordinada?token=123&prefixo_subordinada=0027

# Retorno
# JSON com as agências jurisdicionadas ao prefixo do usuario.
# Content-Type: application/json; charset=utf-8
# Exemplo
# 

###
# .delParametro
# params: token
# necessário usuário estar logado (token) e ter acesso à ferramenta 
PATCH http://localhost:3333/movimentacoes/exclui-parametro?token=123&id=81

# Retorno
# Exclui parâmetro do usuario passando ativo para "0"(softdelete).
# 

# Retorno
# JSON com informações dos parâmetros do prefixo do usuario.
# Content-Type: application/json; charset=utf-8
# Exemplo 
# 

###
# .patchParametros
# params: token
# necessário usuário estar logado (token) e ter acesso à ferramenta Parâmetros 
PATCH http://localhost:3333/movimentacoes/patchParametros?token=123&id=82
Content-Type: application/json

{ "comissaoDestino": "14011","comite": "9009","nomeComissaoDestino": "GER SETOR UA","nomeComite": "CENOP-BH","nomePrefixo": "CENOP-BH","observacao": "teste novo", "prefixoDestino": "1908" }

# Retorno
# Edita os parâmetros do usuario.
# 

# Retorno
# 
# Content-Type: application/json; charset=utf-8
# Exemplo 
# 

###
# .gravarParametro
# params: token
# necessário usuário estar logado (token) e ter acesso à ferramenta Parâmetros 
POST http://localhost:3333/movimentacoes/gravarParametro?token=123
Content-Type: application/json

{ "comissaoDestino": "16261","comite": "1908","nomeComissaoDestino": "GER SETOR UA","nomeComite": "CENOP-BH","nomePrefixo": "CENOP-BH","observacao": "teste novo", "prefixoDestino": "1908" }

# Retorno
# Grava parâmetros do usuario.
# 

###
# .getParametros
# params: token
# necessário usuário estar logado (token) e ter acesso à ferramenta Parâmetros
GET	http://localhost:3333/movimentacoes/testa-parametros?token=123

# Retorno
# JSON com informações dos parâmetros das alçadas
# Content-Type: application/json; charset=utf-8
# Exemplo
# [
#  {
#    "id": 76,
#    "prefixoDestino": "1884",
#    "nomePrefixo": "ESC COMEX ESPECIAL",
#    "comissaoDestino": "04808",
#    "nomecomissaoDestino": "",
#    "comite": "9958",
#    "nomeComite": "UNI-NEG. INTERNAC.",
#    "ativo": "1",
#    "observacao": "",
#    "createdAt": "2022-11-21T21:08:02.000Z",
#    "updatedAt": "21/11/2022 06:08:02"
#  }
#]

###
# .verificarStatusParametro
# params: token
# necessário usuário estar logado (token) e ter acesso à ferramenta 
GET	http://localhost:3333/movimentacoes/verificarStatusParametro?token=123&

# Retorno
# JSON com as agências jurisdicionadas ao prefixo do usuario.
# Content-Type: application/json; charset=utf-8
# Exemplo
# 

###
# .atualizarStatusParametro
# params: token
# necessário usuário estar logado (token) e ter acesso à ferramenta 
GET	http://localhost:3333/movimentacoes/atualizarStatusParametro?token=123&prefixoDestino=0961&comissaoDestino=0610

# Retorno
# JSON com as agências jurisdicionadas ao prefixo do usuario.
# Content-Type: application/json; charset=utf-8
# Exemplo
# 
