module.exports = {
  AnalisesRepository: use('./AnalisesRepository.js'),
  CodigosAusenciaRepository: use('./CodigosAusenciaRepository'),
  DeAcordoRepository: use('./DeAcordoRepository'),
  DocumentosRepository: use('./DocumentosRepository'),
  FuncisRepository: use('./FuncisRepository'),
  HistoricosRepository: use('./HistoricosRepository'),
  LimitrofesRepository: use('./LimitrofesRepository'),
  MailRepository: use('./MailRepository'),
  MunicipiosRepository: use('./MunicipiosRepository'),
  NegativasRepository: use('./NegativasRepository'),
  OptsBasicasRepository: use('./OptsBasicasRepository'),
  PrefixosRepository: use('./PrefixosRepository'),
  PrefixosTesteRepository: use('./PrefixosTesteRepository'),
  SituacoesRepository: use('./SituacoesRepository'),
  SolicitacoesRepository: use('./SolicitacoesRepository'),
  StatusRepository: use('./StatusRepository'),
  TemplatesRepository: use('./TemplatesRepository'),
  TiposHistoricosRepository: use('./TiposHistoricosRepository'),
  TiposRepository: use('./TiposRepository'),
};