module.exports = {
  addParecer: use("App/Commons/HorasExtras/addParecer"),
  addSolicitacao: use("App/Commons/HorasExtras/addSolicitacao"),
  Constants: use("App/Commons/HorasExtras/Constants"),
  getDadosAdesaoHE: use("App/Commons/HorasExtras/getDadosAdesaoHE"),
  getDadosSolicitacao: use("App/Commons/HorasExtras/getDadosSolicitacao"),
  getDadosSolicitacaoHE: use("App/Commons/HorasExtras/getDadosSolicitacaoHE"),
  getResumoGeral: use("App/Commons/HorasExtras/getResumoGeral"),
  getSaldoBHAtual: use("App/Commons/HorasExtras/getSaldoBHAtual"),
  getTotalAutorizadoMes: use("App/Commons/HorasExtras/getTotalAutorizadoMes"),
  obterListaSolicitacoes: use("App/Commons/HorasExtras/obterListaSolicitacoes"),
  obterPeriodos: use("App/Commons/HorasExtras/obterPeriodos"),
  obterStatus: use("App/Commons/HorasExtras/obterStatus"),
  obterRegionais: use("App/Commons/HorasExtras/obterRegionais"),
  podeRealizarDespacho: use("App/Commons/HorasExtras/podeRealizarDespacho"),
  updateSaldoBH: use("App/Commons/HorasExtras/updateSaldoBH"),
  funcoesHora: use("App/Commons/HorasExtras/funcoesHora"),
  isSolicitacaoDespachavelFunci: use("App/Commons/HorasExtras/isSolicitacaoDespachavelFunci"),
  isSuper: use("App/Commons/HorasExtras/isSuper"),
  getResumo: use("App/Commons/HorasExtras/getResumo"),
  isPrefixoSuperAdm: use("App/Commons/HorasExtras/isPrefixoSuperAdm"),
  isAutorizado: use("App/Commons/HorasExtras/isAutorizado"),
  testes: use("App/Commons/HorasExtras/testes"),
  getListaDiasUteis: use("App/Commons/HorasExtras/getListaDiasUteis"),
  getAcessoTeste: use("App/Commons/HorasExtras/getAcessoTeste"),
}